### ISSUE TITLE
Undefined index: scheme

### ISSUE THREAD

**Issue by sharik709** [Kong/unirest-php#134]
ON /vendor/mashape/unirest-php/src/Unirest/Request.php line 545

```
$scheme = $url_parsed['scheme'] . '://';
```

I have installed php-curl and php7.1-curl. But still I'm getting this error message
```Undefined index: scheme```. 

Google says it is happening because of missing curl package but I have installed them. Is there any specific package I must install?. How can I solve this issue?

Please help.
Thank you.

**Comment by ahmadalfy** [comment]
I have the same issue, have you resolved it?

**Comment by sharik709** [comment]
No, I ended up using alternative package.

**Comment by ahmadalfy** [comment]
OK if any one is wondering I resolved it by running:

```
composer dumpautoload
php artisan cache clear
php artisan config cache
```
